FROM ubuntu:18.04

RUN apt-get update && apt-get install -y gcc

WORKDIR /MyProj_231_Zotov

COPY . /MyProj_231_Zotov

RUN gcc -o my_Program main.c

ENV MY_PROGRAM_PARAM=default_value

CMD ["./my_Program", "$MY_PROGRAM_PARAM"]